project:
  type: website
  output-dir: docs
website:
  title: "Jorge D. Mello-Román"
  navbar:
    left:
      - href: index.qmd
        text: Inicio
      - href: publicaciones.qmd
        text: Publicaciones
      - href: cv.qmd
        text: CV
      - href: about.qmd
        text: Sobre mí

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    lang: es

